### ISSUE TITLE
DevOps task: Failed to get personal access token for long model extraction

### ISSUE THREAD

**Issue by CRidge** [MicrosoftDocs/intellicode#387]
I'm trying to get the DevOps "IntelliCode Team Model Training" task to work for our solution. I'm using classic pipeline, but the XAML-exported step look like this:

```
steps:
- task: VisualStudioExptTeam.VSIntelliCodeTeamModelTraining.intellicode-endpoint-type.IntelliCodeTeamModels@1
  displayName: 'IntelliCode Team Models '
  inputs:
    intelliCodeServiceEndpoint: 'IntelliCode Lab'
```

The intelliCode endpoint has been setup by me (with admin rights) and authorized. However, I get this in my output whatever I try to do, before the step fails:

```
CLI Warning: 0 : Failed to get personal access token for long model extraction.
CLI Error: 0 : Temporary personal access token could not be retrieved from the server.
```
I find no reference to these errors online. I have enabled "Allow scripts to access the OAuth token" for the pipeline, by the way.

I'm glad to share more info about my setup, but I don't know what is relevant and would most like to know what these errors actually mean.
