### ISSUE TITLE
[IntelliCode API Usage Examples] CSS background bug in code snippet previews

### ISSUE THREAD

**Issue by ThenTech** [MicrosoftDocs/intellicode#588]
Due to https://github.com/microsoft/vscode/pull/197124 introducing a new CSS variable `--vscode-textPreformat-background`, all code blocks rendered in Markdown context have a background color set. But the way the IntelliCode API Usage Examples extension renders its snippets, this background color is also applied to all the text in the snippet, visually looking like the entire snippet is always selected:

![Image](https://github.com/user-attachments/assets/60ddaab9-c5e5-4acb-926b-bb517045492c )

As a solution, the `gaia-results.css` could override the `background-color` property to transparent in the `pre code` style:
```css
pre code {
    color: var(--vscode-editor-foreground);
    tab-size: 4;
    background-color: transparent; /* Changed */
}
```

Which will then look like below, which is the expected behaviour I assume.

![Image](https://github.com/user-attachments/assets/5b96cf0c-a06f-4dca-a63f-b7e3fde547e9)
